### ISSUE TITLE
 Can I add recipe to conan-center-index?

### ISSUE THREAD

**Issue by tt4g** [google/fruit#100]
I am thinking of adding a fruit recipe to [conan-center-index](https://github.com/conan-io/conan-center-index).
However, there was an inclusion request to Conan Center a year ago (#83).
I should not add recipes to conan-center-index if this is going on.

I think it's best for the library developer to maintain the conan recipe as well.
However, if your work is not progressing, I would like to add a recipe to conan-center-index.

What do you think?

**Comment by poletti-marco** [comment]
I'm not actively working on that, feel free to add it. (and thanks!)

**Comment by tt4g** [comment]
Thank you for response.

I pull request in conan-center-index: conan-io/conan-center-index#1011
