### ISSUE TITLE
Unable to unzip source file archive

### ISSUE THREAD

**Issue by tt4g** [google/fruit#107]
I am creating a fruit conan recipe (conan-io/conan-center-index#1011).
There is one problem here and I need your help.

The conan recipe downloads the source file archive from the following GitHub release URL: https://github.com/google/fruit/archive/v3.4.0.tar.gz

When unzip this archive, I find files `build` and `BUILD` in directory `fruit-3.4.0/extras/bazel_root/third_party/fruit/`.
In a case-insensitive file system, two file names conflict and the archive decompression fails.

Since the contents of these two files are the same, I think that one is enough.
Is it possible to delete one of the files and update the fruit 3.4.0 release page?

**Comment by poletti-marco** [comment]
> Since the contents of these two files are the same, I think that one is enough.

Agreed, not sure how the lowercase one ended up there.
I deleted that now.

> Is it possible to delete one of the files and update the fruit 3.4.0 release page?

The archives in the releases page are auto-generated when I tag a new release, I don't think they can be manually edited after the fact.
I could create a new release though. I'll try to get the CI back to all green (especially the windows one) tomorrow and then create a new release, that will no longer have the "build" file in that dir.

**Comment by tt4g** [comment]
I really appreciate your great support.

**Comment by poletti-marco** [comment]
Fruit 3.5.0 is released, so this should no longer be an issue even if using a tagged release.
Closing.

**Comment by tt4g** [comment]
👍
