### ISSUE TITLE
Add vcpkg installation instructions

### ISSUE THREAD

**Issue by LilyWangL** [google/fruit#112]
`fruit` is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `fruit` and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `fruit`, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (Linux, Windows: x86, x64) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/fruit/portfile.cmake). We try to keep the library maintained as close as possible to the original library.

I'm trying to add vcpkg installation instructions but I couldn't find the related docs in code item except for on `Wiki` page.

Could you please help add the following contents to this port?

```
Installing and building fruit via vcpkg

You can download and install fruit using the [vcpkg](https://github.com/Microsoft/vcpkg) dependency manager:

      git clone https://github.com/Microsoft/vcpkg.git
      cd vcpkg
      ./bootstrap-vcpkg.sh
      ./vcpkg integrate install
      vcpkg install fruit

The freerdp port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please [create an issue or pull request](https://github.com/Microsoft/vcpkg) on the vcpkg repository.
```
The similar pull request like this https://github.com/google/glog/pull/517.

Thanks,
Lily

**Comment by poletti-marco** [comment]
I think the wiki is the right place. That's where the rest of the
installation instructions are.
Why would you like to add something in the fruit codebase too?

**Comment by poletti-marco** [comment]
Added that info here (rephrased/summarized a bit):

https://github.com/google/fruit/wiki/Install#with-vcpkg-on-windows-not-ufficially-supported
