### ISSUE TITLE
Small windows compiling error

### ISSUE THREAD

**Issue by Max9403** [google/fruit#127]
This seems too simple to be worth a pull request but line 50 in `fruit/impl/data_structures/semistatic_map.h`

```std::numeric_limits<NumBits>::max()```
needs to be changed to 
```(std::numeric_limits<NumBits>::max)()```

To fix a mix up with the max macro from a Window's header (extra info: https://stackoverflow.com/questions/27442885/syntax-error-with-stdnumeric-limitsmax)

**Comment by poletti-marco** [comment]
Hi, thanks for reporting!
I fixed this in 125c403.
