### ISSUE TITLE
Fruit with QT

### ISSUE THREAD

**Issue by AndreiGS** [google/fruit#146]
Hello!

I'm new to Fruit and QT and I could really use some help. I've created a "backend", but not as a server, just the logic of it, and I am trying to bring it into the Qt project either by using a static library or moving the project as a whole. The thing is that when using the backend as a separate project, everything works fine, but when trying to create the injector for any of the dependencies into the qt project, it throws an error in xmemory. Has anyone tried this before? 

Thank you for reading the message! :)

**Comment by poletti-marco** [comment]
Hi, I'm not familiar with Qt so I'm going to need more information on what you're doing.
Can you please share an (ideally minimal) example code and commands that can be used to reproduce the issue?
See https://stackoverflow.com/help/minimal-reproducible-example

**Comment by AndreiGS** [comment]
Let's say I have this repository, the base repository is just a simple template repository with basic functionality in it

```
class IUserRepository : public BaseRepository<User, uint16_t>
{
public:
	~IUserRepository() override = default;

	virtual std::optional<User> FindByName(const std::string& name) = 0;
};
```

This is the implementation header:
```
class UserRepository : public IUserRepository
{
public:
	INJECT(UserRepository()) = default;
	~UserRepository() override = default;

	std::optional<User> FindByName(const std::string& name) override;
};

fruit::Component<IUserRepository> getUserRepositoryComponent();
```

And this is the implementation:
```
std::optional<User> UserRepository::FindByName(const std::string& name)
{
	using namespace sqlite_orm;
	try {
		auto guard = k_Database.transaction_guard(); //  calls BEGIN TRANSACTION and returns guard object
		auto entity = k_Database.get_all<User>(where(c(&User::GetName) == name)); //  exception is thrown here, guard calls ROLLBACK in its destructor
		guard.commit();
		if (entity.empty())
		{
			return std::nullopt;
		}
		return std::make_optional(std::move(entity[0]));
	}
	catch (...) {
		return std::nullopt;
	}
}

fruit::Component<IUserRepository> getUserRepositoryComponent()
{
	return fruit::createComponent().bind<IUserRepository, UserRepository>();
}
```

When doing this:
```
fruit::Injector<IUserRepository> inj{ getUserRepositoryComponent };
IUserRepository* service(inj);

auto rsp = service->FindByName("Iris");
```

in the backend app it works fine, but the exact same code used in the main.cpp of the qQTproject throws an error when initializing the injector, maybe because it cannot create the binding? I do not think it is a linking error because it happens even if I move all the backend files into the QT project.


Thank you for the help!

**Comment by poletti-marco** [comment]
I don't see anything wrong in the code you provided, so either the issue is an undefined behavior elsewhere in your code (the code provided has several references to things not defined in the provided code) or a platform/installation issue.

What OS are you using? Fruit supports Linux, windows, MacOS.

How did you install Fruit? From source, with binary packages, etc.
If from source, did you build fruit using cmake or something else?
What version of Fruit are you using?

What compiler are you using? GCC, clang, etc.

You mentioned that there's an error when creating the injector, can you please provide the exact error?

**Comment by AndreiGS** [comment]
Sorry for the late response. I am using Windows 10 x64 with Visual Studio 2022 and Fruit was installed using vcpkg and the version is the latest. I cannot provide the exact error because I had to remove Fruit from the project, but it was that it cannot access some memory address.
