### ISSUE TITLE
Argument Order with Assisted Types with Functors

### ISSUE THREAD

**Issue by zdevzee** [google/fruit#18]
Some code was being tested for use in another project, and a weird (sort of) error occurred.  When using assisted types in a constructor, it was found that for some reason (is it in the tutorial / wiki ?), the order for the function defintion is reversed.  In this case, the function for 'registerFactory' is being automatically generated (whcih relies on the function defiintion in the return type).  However, when the order of the arguments is reversed, it compiles correctly, and runs!  Is there an explanation for this behaviour.  It's presumed that when the return fucntion is generated (possibly without explicitly defining registerFactory), that the loop starts at the end and iterates backwards (or vice versa).  Here is some sample code:

    using Inject = LoggerImpl(fruit::Assisted<int>, fruit::Assisted<float>);
    LoggerImpl( int argc , float argv) {
         ...do stuff with argc, argv
    }

using LoggerFactory = function<unique_ptr<LoggerImpl>(float,int)>;

fruit::Component<LoggerFactory> getLoggerComponentA() {
    return fruit::createComponent().bind<Logger, LoggerImpl>();
}

The error that occurs when its in the correctly (intuitively? / or normally) order is as follows:

n file included from fruit/include/fruit/fruit.h:25:0,
                 from fruit_test_main.cpp:9:
fruit/include/fruit/impl/injection_errors.h: In instantiation of 'struct fruit::impl::FunctorSignatureDoesNotMatchError<LoggerImpl(int, float), LoggerImpl(float, int)>':
fruit/include/fruit/impl/component.defn.h:58:55:   required from 'fruit::Component<Types>::Component(fruit::PartialComponent<Bindings ...>) [with Bindings = {fruit::impl::Bind<Logger, LoggerImpl>}; Params = {std::function<std::unique_ptr<LoggerImpl, std::default_delete<LoggerImpl> >(int, float)>}]'
Logger.hpp:101:62:   required from here
fruit/include/fruit/impl/injection_errors.h:214:3: error: static assertion failed: Unexpected functor signature (it should be the same as ExpectedSignature minus any Assisted types).
   static_assert(
   ^~~~~~~~~~~~~
In file included from fruit/include/fruit/component.h:498:0,
                 from fruit/include/fruit/fruit.h:28,
                 from fruit_test_main.cpp:9:
fruit/include/fruit/impl/component.defn.h: In instantiation of 'fruit::Component<Types>::Component(fruit::PartialComponent<Bindings ...>) [with Bindings = {fruit::impl::Bind<Logger, LoggerImpl>}; Params = {std::function<std::unique_ptr<LoggerImpl, std::default_delete<LoggerImpl> >(int, float)>}]':
Logger.hpp:101:62:   required from here
fruit/include/fruit/impl/component.defn.h:61:135: error: no type named 'Result' in 'fruit::impl::meta::OpForComponent<fruit::impl::Bind<Logger, LoggerImpl> >::ConvertTo<fruit::impl::meta::Comp<fruit::impl::meta::Vector<>, fruit::impl::meta::Vector<fruit::impl::meta::Type<std::function<std::unique_ptr<LoggerImpl, std::default_delete<LoggerImpl> >(int, float)> > >, fruit::impl::meta::Vector<fruit::impl::meta::Pair<fruit::impl::meta::Type<std::function<std::unique_ptr<LoggerImpl, std::default_delete<LoggerImpl> >(int, float)> >, fruit::impl::meta::Vector<> > >, fruit::impl::meta::Vector<>, fruit::impl::meta::EmptyList> > {aka struct fruit::impl::meta::Error<fruit::impl::FunctorSignatureDoesNotMatchErrorTag, LoggerImpl(int, float), LoggerImpl(float, int)>}'
 mpl::meta::Eval<fruit::impl::meta::CheckNoLoopInDeps(typename Op::Result)>>::type();
                                                                              ^~~~~~
fruit/include/fruit/impl/component.defn.h:64:7: error: no match for call to '(Op {aka fruit::impl::meta::Error<fruit::impl::FunctorSignatureDoesNotMatchErrorTag, LoggerImpl(int, float), LoggerImpl(float, int)>}) (fruit::impl::ComponentStorage&)'
   Op()(storage);

(Note Logger.hpp and fruit_test_main.cpp are the two source files - the full directories have been removed, etc).

With the code:
using LoggerFactory = function<unique_ptr<LoggerImpl>(int,float)>;
...
    Injector<LoggerFactory> injector(getLoggerComponentA());
    LoggerFactory loggerFactory(injector);
    unique_ptr<Logger> logger = loggerFactory(argc,5.0f);

Please advise, thank you.  This solutions seems (pretty) good, and it may be helpful, but this error caused issues!
Is it necessary to supply the registerFactory call with an explicitly defined functor/lambda, and is it necessary to reverse the argument order in that call as well?

Thanks again!

**Comment by poletti-marco** [comment]
What version of Fruit is this? There was a bug (well, 2 actually) in Fruit <2.0.2 that could have caused this behavior. If you're using a Fruit version older than that, please upgrade.
If it's more recent, this is a separate issue; in that case, please provide a self-contained example code that shows the issue (so I can try to reproduce).

**Comment by zdevzee** [comment]
Hey, thanks (also, this project is very cool)!  Version 2.0.4 was tried (the code was downloaded from the tags page, where the changes for each tagged version is displayed).  In that code, the bug / issue is fixed!  The code downloaded (through git clone using the default options) though should have been the most up to date, for some reason it didn't include the resolution.

**Comment by poletti-marco** [comment]
Strange, git master should also work. (after catching the bug I added tests for these cases). I'll look into that, reopening this issue so that I remember to do it.

**Comment by zdevzee** [comment]
The master/head git repository was tried, and it seems to run and compile fine.  Perhaps, somehow the wrong branch/tag was downloaded originally.  Apologies for bringing up and old issue.

**Comment by poletti-marco** [comment]
Oh, I see. Thanks for checking. Re-closing this then.
