### ISSUE TITLE
Missing "free" reference

### ISSUE THREAD

**Issue by beoboo** [google/fruit#3]
Using a brand new MAC OS environment, there is a compilation error:

    /works/cpp/fruit/src/demangle_type_name.cpp:32:5: error: use of undeclared identifier 'free'
    free(demangled_name);

that can be fixed by adding:

    #include <cstdlib> 

in the same file.

**Comment by poletti-marco** [comment]
Thanks for the report!
FIxed in https://github.com/google/fruit/commit/4250ef671da6c72a8f3608e25c982ff8899ffaf2
Let me know if there are any further issues on OS X, I don't have a Mac so can't test myself, but happy to fix any issues you might find.
