### ISSUE TITLE
Investigate switch to constexpr-based metafunctions

### ISSUE THREAD

**Issue by poletti-marco** [google/fruit#38]
Using the `__PRETTY_FUNCTION__`-in-a-template-function trick to have a compile-time ID of a type.

This would allow to use "throw ..." instead of simulating exception handling in the metafunction implementation.

**Comment by fran6co** [comment]
Check https://github.com/Manu343726/ctti for an implementation. This would help adding support for Visual Studio as it doesn't support to use `typeid` in constexpr expressions.

**Comment by poletti-marco** [comment]
> This would help adding support for Visual Studio as it doesn't support to use typeid in constexpr expressions.

@fran6co probably knows now, but for anyone else that reads this, VS is now supported without doing this change.
This change might still be worthwile though (but it's not going to be a game-changer from the Fruit user's perspective, it's mostly a refactor to Fruit internals).

**Comment by poletti-marco** [comment]
When using a couple (simple) constexpr functions, there was a major compile-time slowdown with GCC 6 (~2x), so I've now reverted those changes.
So this enhancement doesn't seem valuable anymore, it would likely make compilation time a lot worse (and it would have no effect on runtime). Closing as "won't fix".
