### ISSUE TITLE
Other cmake build types

### ISSUE THREAD

**Issue by mpapierski** [google/fruit#45]
I'm using `RelWithDebInfo` while including `fruit` as a subdirectory (related issue: #44)  and I noticed that I can't configure my project anymore.

The specific problem is those lines https://github.com/google/fruit/blob/f5c96b3191d4db6df4024ce5c8c23a36dd35a566/CMakeLists.txt#L11-L13 that forbids any other build type to be used in `fruit`.

Is there reason to restrict builds just to `Debug`/`Release` configurations? In case of including `fruit` as part of a build system `CMAKE_BUILD_TYPE` might be any of those mentioned in `cmake-variables(7)`.

**Comment by poletti-marco** [comment]
Thanks for the report. This check was indeed overly restrictive.
Fixed in c7cfd025184ddf4a2d11a58aad04e4ac0aa3236f.
