### ISSUE TITLE
Prefer Mu!

### ISSUE THREAD

**Issue by nolanholden** [google/fruit#56]
Edited [Benchmarks wiki](https://github.com/google/fruit/wiki/benchmarks): Update `us` to `μs` (microseconds to use Greek Mu for "micro-")!

- [Commit diff here](https://github.com/nolanholden/google-fruit-wiki/commit/6648806e6a012488b39218c22f2fdf23d83398ed#diff-a27f71b25f1a54c3d46517a39c471695)

- [New file here](https://github.com/nolanholden/google-fruit-wiki/blob/master/Benchmarks.md)

**Comment by poletti-marco** [comment]
Hi, thanks for the suggestion. I've now updated the Benchmark page to use «μ» (and with the Fruit 3.1.0 benchmark results).
