### ISSUE TITLE
Packages/Build for armv7l 

### ISSUE THREAD

**Issue by qgicup** [google/fruit#59]
Would be really great if we can build fruit for armv7l, as it can greatly be used in IoT devices.

Can you package it please for armv7l ? In my case it was not successful due following error while compiling :

1)With boost

````
::HashMapWithArenaAllocator<fruit::impl::TypeId, fruit::impl::ComponentStorageEntry> = boost::unordered::unordered_map<fruit::impl::TypeId, fruit::impl::ComponentStorageEntry, std::hash<fruit::impl::TypeId>, std::equal_to<fruit::impl::TypeId>, fruit::impl::ArenaAllocator<std::pair<const fruit::impl::TypeId, fruit::impl::ComponentStorageEntry> > >]’:
/home/buddy/work/fruit/include/fruit/impl/normalized_component_storage/binding_normalization.templates.h:50:109: internal compiler error: Segmentation fault
         toplevel_entries.begin(), toplevel_entries.end(), ArenaAllocator<ComponentStorageEntry>(memory_pool)) {
                                                                                                             ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
Preprocessed source stored into /tmp/cc1l6ecr.out file, please attach this to your bugreport.
```

2) Without boost

````

/usr/local/sbin/bg/.data/firmware/fruit/src/binding_normalization.cpp:433:50:   required from here
/usr/include/c++/4.8/bits/hashtable.h:727:6: error: 'std::_Hashtable<fruit::impl::ComponentStorageEntry::LazyComponentWithNoArgs, fruit::impl::ComponentStorageEntry::LazyComponentWithNoArgs, fruit::impl::ArenaAllocator<fruit::impl::ComponentStorageEntry::LazyComponentWithNoArgs>, std::__detail::_Identity, std::equal_to<fruit::impl::ComponentStorageEntry::LazyComponentWithNoArgs>, fruit::impl::NormalizedComponentStorage::HashLazyComponentWithNoArgs, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, true, true> >::_Node_allocator_type' has no member named 'construct'
/usr/local/sbin/bg/.data/firmware/fruit/include/fruit/impl/normalized_component_storage/binding_normalization.templates.h:50: confused by earlier errors, bailing out
````

**Comment by poletti-marco** [comment]
Hi, I've now added pre-built binary packages for ARM (both armv7l and aarch64) for the following distributions:
* Debian 9.0
* Fedora 25
* Fedora 26
* Fedora 27
* Ubuntu 16.10

You can find them [here](http://software.opensuse.org/download.html?project=home%3Apoletti_marco&package=libfruit) (together with the other binary packages).

You can also build Fruit manually (e.g. if you're using a distribution that's not in the list above), following the instructions [here](https://github.com/google/fruit/wiki/install#prebuilt-packages).
However note that GCC 4.8.x isn't supported by Fruit 3.0.0, if you want to compile using GCC you'll have to install a version >=5.0.0. You can find more details about supported compilers and libraries in the [install page of the wiki](https://github.com/google/fruit/wiki/install#dependencies).

Hope that helps.
Feel free to re-open if you're still having problems with building on ARM and/or installing these binary packages.
