### ISSUE TITLE
Using Fruit sources instead of building

### ISSUE THREAD

**Issue by Octogonapus** [google/fruit#62]
I want to use Fruit for an embedded project that is compiled with Make, so I want to add Fruit as a submodule and compile with the sources directly instead of first building Fruit and then linking with it. I have Fruit's include directory added to my include path but I am getting an error:

```
include/fruit/impl/fruit-config.h:20:10: fatal error: fruit/impl/fruit-config-base.h: No such file or directory
 #include <fruit/impl/fruit-config-base.h>
```

Indeed, the file `fruit/impl/fruit-config-base.h` is not present. Is this file autogenerated by something, and therefore I am missing it? Or have I missed an earlier setup step?

I have Fruit checked out at release `v3.1.1` and I am compiling with `arm-none-eabi-g++ 7.2.1` on Ubuntu 16.04.

**Comment by poletti-marco** [comment]
That file is auto-generated by CMake, so if don't run cmake first you won't be able to build Fruit.

It's not clear to me why you want to build Fruit as part of the other project. Could you please explain in a bit more detail why you want to do that?

Note that you *can* build Fruit separately as a static library and then link that into your main executable (if your goal is to avoid a dynamic library).

You also could invoke {cmake, then make, then make install pointed at a local dir} as actions in one of your parent project's makefiles if that's what you want.

**Comment by Octogonapus** [comment]
I want to include Fruit's sources directly because the target is an embedded device, and I didn't want to work out all the compiler flags to get Fruit compiled correctly for that platform. Maybe I am misunderstanding how that works, though. I will run CMake and see where that gets me. Thanks.

**Comment by Octogonapus** [comment]
I found a toolchain file here that looks like it would help: https://github.com/vpetrigo/arm-cmake-toolchains/blob/master/arm-gcc-toolchain.cmake

I am still getting an expected error, however: https://pastebin.com/hFktzrT9
`undefined reference to _exit` seems to be usually solved by adding `set(CMAKE_EXE_LINKER_FLAGS_INIT "--specs=nosys.specs")` to the toolchain file, which I have done. I am building with the command
```
cmake -DCMAKE_TOOLCHAIN_FILE=arm-gcc-toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DFRUIT_USES_BOOST=False .
```

I'm not sure what to do, it seems like CMake is ignoring `--specs=nosys.specs`.

**Comment by poletti-marco** [comment]
https://cmake.org/cmake/help/v3.7/variable/CMAKE_EXE_LINKER_FLAGS_INIT.html

The documentation says that this is only taken into account when creating the cmake cache. Did you clean the cake cache after adding that? If you ran cmake before, it will have created a CMakeCache.txt file in the root directory that you'll have to remove.
There should also be a CMakeFiles that you might need to remove so that it gets re-created (or maybe not, not sure about this).

**Comment by poletti-marco** [comment]
s/cake/cmake/ :-)

**Comment by Octogonapus** [comment]
Looks like I also have to remove the CMakeFiles directory, thanks. Looks like I am still getting the same error, though. Just with your message: `A trivial program with an empty main doesn't compile, something is wrong with your compiler and/or with your compiler flags.`

**Comment by poletti-marco** [comment]
I finally got around to spend some time on this and I've found a way to make it work.

1. Save these lines as an `arm-toolchain.cmake` file:

    set(CMAKE_SYSTEM_NAME Generic)
    set(CMAKE_SYSTEM_PROCESSOR arm)
    set(CMAKE_C_COMPILER arm-none-eabi-gcc)
    set(CMAKE_CXX_COMPILER arm-none-eabi-g++)

2. Cherrrypick commit 155b57e98fb15769b1e5fb99154884b195df0b61 (this will be in the next release, so after that release you'll no longer need to cherrypick this.

    git clone git@github.com:google/fruit.git
    cd fruit
    git checkout v3.1.1
    git cherry-pick 155b57e98fb15769b1e5fb99154884b195df0b61

And finally run CMake as follows:

    LDFLAGS=--specs=nosys.specs cmake -DCMAKE_TOOLCHAIN_FILE=arm-toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=False -DFRUIT_USES_BOOST=False .

Then you can run make as usual, e.g.:

    make -j 4

Hope that this helps!

**Comment by Octogonapus** [comment]
That works great, thanks!
