### ISSUE TITLE
undefined reference to `fruit::impl::MemoryPool::destroy()'

### ISSUE THREAD

**Issue by jjangga0214** [google/fruit#64]
I tried to get started fruit with the exact same code with [here](https://github.com/google/fruit/wiki/tutorial:-getting-started),   
but get the errors when to compile my project  using fruit  
(e.g `undefined reference to fruit::impl::MemoryPool::destroy()`).

I am using ubuntu 16.04 and manually built(cmake and make fruit to /usr/local) fruit-3.1.1.

Is this a bug or should I do something more?

```
CMakeFiles/battleship-0.0.1.out.dir/main.cpp.o: In function `fruit::impl::MemoryPool::~MemoryPool()':
/usr/local/include/fruit/impl/data_structures/memory_pool.defn.h:55: undefined reference to `fruit::impl::MemoryPool::destroy()'
CMakeFiles/battleship-0.0.1.out.dir/main.cpp.o: In function `fruit::impl::SemistaticGraph<fruit::impl::TypeId, fruit::impl::NormalizedBinding>::at(fruit::impl::TypeId)':
/usr/local/include/fruit/impl/data_structures/semistatic_graph.defn.h:131: undefined reference to `fruit::impl::SemistaticMap<fruit::impl::TypeId, fruit::impl::SemistaticGraphInternalNodeId>::at(fruit::impl::TypeId) const'
CMakeFiles/battleship-0.0.1.out.dir/main.cpp.o: In function `fruit::Injector<Greeter>::Injector<>(fruit::Component<Greeter> (*)())':
/usr/local/include/fruit/impl/injector.defn.h:38: undefined reference to `fruit::impl::InjectorStorage::InjectorStorage(fruit::impl::ComponentStorage&&, std::vector<fruit::impl::TypeId, fruit::impl::ArenaAllocator<fruit::impl::TypeId> > const&, fruit::impl::MemoryPool&)'
CMakeFiles/battleship-0.0.1.out.dir/main.cpp.o: In function `std::default_delete<fruit::impl::InjectorStorage>::operator()(fruit::impl::InjectorStorage*) const':
/usr/include/c++/5/bits/unique_ptr.h:76: undefined reference to `fruit::impl::InjectorStorage::~InjectorStorage()'
collect2: error: ld returned 1 exit status
CMakeFiles/battleship-0.0.1.out.dir/build.make:146: 'Debug/battleship-0.0.1.out' 타겟에 대한 명령이 실패했습니다
make[2]: *** [Debug/battleship-0.0.1.out] 오류 1
make[2]: 디렉터리 '/home/user/문서/projects/battleship' 나감
CMakeFiles/Makefile2:70: 'CMakeFiles/battleship-0.0.1.out.dir/all' 타겟에 대한 명령이 실패했습니다
make[1]: *** [CMakeFiles/battleship-0.0.1.out.dir/all] 오류 2
make[1]: 디렉터리 '/home/user/문서/projects/battleship' 나감
Makefile:86: 'all' 타겟에 대한 명령이 실패했습니다
make: *** [all] 오류 2

```

**Comment by jjangga0214** [comment]
I followed commands [here](https://github.com/google/fruit/wiki/install#building-fruit-manually).

Let me assume I unzip the downloaded file(Fruit 3.1.1 -> Source code (tar.gz) from [here](https://github.com/google/fruit/releases)) and its name is ${FRUIT}

```
cd ${FRUIT}

sudo chmod -R 777 ./

cmake -DCMAKE_BUILD_TYPE=Release -DFRUIT_USES_BOOST=False . && make -j

sudo make install
```
My gcc version is 5.5.0.

And I haven't installed Prebuilt packages.

**Comment by poletti-marco** [comment]
Hi, looking at your CMakeLists.txt file:
https://github.com/jjangga0214/cpp-fruit-demo/blob/master/CMakeLists.txt

It doesn't seem to link to Fruit.
You should add this at the end of the file:

    target_link_libraries(cpp_fruit_demo fruit)

See the example CMakeLists.txt file here:
https://github.com/google/fruit/blob/master/examples/hello_world/CMakeLists.txt

Please close this issue if that works, or let me know if it's still not working and I can help debug this further.

**Comment by jjangga0214** [comment]
Thank you so much.
Adding
```cmake
target_link_libraries(cpp_fruit_demo fruit)
```
after `add_executable(cpp_fruit_demo main.cpp)` on _CMakeList.txt_  
and 
```
export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib
```
for my linux to find shared libraries
make the source compiled.
