### ISSUE TITLE
how to install setup pfunit for fortran unit testing

### ISSUE THREAD

**Issue by anooshtahir** [google/fruit#65]
I have downloaded pfUnit from SourceForge from given link:
[pfUnit](https://sourceforge.net/projects/pfunit/)
I have Intel Fortran (Using with Visual Studio) someone please guide how to download, setup and run testcase on pFunit.

**Comment by poletti-marco** [comment]
Hi, maybe you followed the wrong link, this is the issue tracker for Fruit, a library for C++.
This is not related to Fortran.
