### ISSUE TITLE
Allow building as a static library

### ISSUE THREAD

**Issue by mjkoo** [google/fruit#7]
It would be nice if there was an option to build fruit as a static library, currently the SHARED argument in the add_library() call in src/CMakeLists.txt seems to prevent overriding this behavior on the cmake command line.

**Comment by poletti-marco** [comment]
Thanks for the pull request, merged now.
Sorry again for having you accept that agreement; on the plus side it's a one-time thing so if you'll send any more pull requests that will no longer be needed.
