### ISSUE TITLE
Is fruit working with the c++ compiler of Visual Studio 2010?

### ISSUE THREAD

**Issue by zadigus** [google/fruit#70]
Hi,
I am looking for a DI framework and currently I have only found one framework that meets my requirements. In my company, we are working with a pretty old c++ compiler, that of visual studio 2010 (which uses some features of c++11). I think it's c++03 or something. 
Do you happen to know if your framework is compatible with that compiler?
Thanks in advance!

**Comment by poletti-marco** [comment]
Hi, I wish it did, but I'm afraid it's not going to work.

MSVC 2015 is the earliest supported version, see https://github.com/google/fruit/wiki/install.

Fruit uses variadic templates (a C++11 feature) heavily, even getting MSVC 2015 to work was non-trivial, it required workarounds in quite a few places of the code.
Realistically, i think MSVC 2010 is probably never going to be supported.
