### ISSUE TITLE
wiki: Benchmarks: error on CPU spec

### ISSUE THREAD

**Issue by thomas-riccardi** [google/fruit#73]
On https://github.com/google/fruit/wiki/benchmarks it says
> All the following benchmarks have been executed on an AMD Ryzen Threadripper 1950X @3.4GHz (16 virtual cores)

However, the `AMD Ryzen Threadripper 1950X` has 16 real cores, and 32 threads as documenter here: https://www.amd.com/en/products/cpu/amd-ryzen-threadripper-1950x#product-specs

**Comment by poletti-marco** [comment]
Oh, well spotted. Fixed now, thanks for reporting this.
