### ISSUE TITLE
Build errors from header files after successful Cmake build and install

### ISSUE THREAD

**Issue by djsing** [google/fruit#84]
Following the tutorial, I built the library using cmake successfully.  I included the header files in the hello world example project and linked it to the library. I added -lfruit to the complier command as said in the tutorial. Any time I include the fruit header files I get this error:

C:\WINDOWS\system32\cmd.exe /C C:/mingw64/bin/mingw32-make.exe -j4 SHELL=cmd.exe -e -f  Makefile
"----------Building project:[ h - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'C:/Users/darri/Desktop/dev3project/h'
C:/mingw64/bin/g++.exe --std=c++17 -lfruit  -c  "C:/Users/darri/Desktop/dev3project/h/main.cpp" -g -O0 -Wall  -o ./Debug/main.cpp.o -I. -IC:\googleFruit\include
In file included from C:\googleFruit\include/fruit/impl/data_structures/memory_pool.h:63:0,
                 from C:\googleFruit\include/fruit/impl/data_structures/arena_allocator.h:20,
                 from C:\googleFruit\include/fruit/impl/util/type_info.defn.h:23,
                 from C:\googleFruit\include/fruit/impl/util/type_info.h:111,
                 from C:\googleFruit\include/fruit/impl/data_structures/fixed_size_allocator.h:22,
                 from C:\googleFruit\include/fruit/impl/injector/injector_storage.h:21,
                 from C:\googleFruit\include/fruit/impl/component_functors.defn.h:24,
                 from C:\googleFruit\include/fruit/component.h:25,
                 from C:\googleFruit\include/fruit/fruit.h:27,
                 from C:/Users/darri/Desktop/dev3project/h/main.cpp:2:
C:\googleFruit\include/fruit/impl/data_structures/memory_pool.defn.h:55:21: error: duplicate 'inline'
 FRUIT_ALWAYS_INLINE inline T* MemoryPool::allocate(std::size_t n) {
                     ^~~~~~
In file included from C:\googleFruit\include/fruit/impl/data_structures/fixed_size_allocator.h:118:0,
                 from C:\googleFruit\include/fruit/impl/injector/injector_storage.h:21,
                 from C:\googleFruit\include/fruit/impl/component_functors.defn.h:24,
                 from C:\googleFruit\include/fruit/component.h:25,
                 from C:\googleFruit\include/fruit/fruit.h:27,
                 from C:/Users/darri/Desktop/dev3project/h/main.cpp:2:
C:\googleFruit\include/fruit/impl/data_structures/fixed_size_allocator.defn.h:66:21: error: duplicate 'inline'
 FRUIT_ALWAYS_INLINE inline fruit::impl::meta::UnwrapType<
                     ^~~~~~
In file included from C:\googleFruit\include/fruit/impl/component_install_arg_checks.h:31:0,
                 from C:\googleFruit\include/fruit/impl/component_function.defn.h:22,
                 from C:\googleFruit\include/fruit/component_function.h:68,
                 from C:\googleFruit\include/fruit/impl/component_storage/component_storage_entry.defn.h:23,
                 from C:\googleFruit\include/fruit/impl/component_storage/component_storage_entry.h:341,
                 from C:\googleFruit\include/fruit/impl/normalized_component_storage/normalized_bindings.h:20,
                 from C:\googleFruit\include/fruit/impl/injector/injector_storage.h:23,
                 from C:\googleFruit\include/fruit/impl/component_functors.defn.h:24,
                 from C:\googleFruit\include/fruit/component.h:25,
                 from C:\googleFruit\include/fruit/fruit.h:27,
                 from C:/Users/darri/Desktop/dev3project/h/main.cpp:2:
C:\googleFruit\include/fruit/impl/component_install_arg_checks.defn.h:29:21: error: duplicate 'inline'
 FRUIT_ALWAYS_INLINE inline int checkAcceptableComponentInstallArg() {
                     ^~~~~~
In file included from C:\googleFruit\include/fruit/impl/meta/algos.h:20:0,
                 from C:\googleFruit\include/fruit/impl/meta/component.h:23,
                 from C:\googleFruit\include/fruit/impl/data_structures/fixed_size_allocator.h:21,
                 from C:\googleFruit\include/fruit/impl/injector/injector_storage.h:21,
                 from C:\googleFruit\include/fruit/impl/component_functors.defn.h:24,
                 from C:\googleFruit\include/fruit/component.h:25,
                 from C:\googleFruit\include/fruit/fruit.h:27,
                 from C:/Users/darri/Desktop/dev3project/h/main.cpp:2:
C:\googleFruit\include/fruit/impl/normalized_component_storage/normalized_bindings.defn.h: In constructor 'fruit::impl::NormalizedBinding::NormalizedBinding(fruit::impl::ComponentStorageEntry)':
C:\googleFruit\include/fruit/impl/fruit-config.h:83:3: error: '__assume' was not declared in this scope
   __assume(0)
   ^
C:\googleFruit\include/fruit/impl/normalized_component_storage/normalized_bindings.defn.h:47:5: note: in expansion of macro 'FRUIT_UNREACHABLE'
     FRUIT_UNREACHABLE; // LCOV_EXCL_LINE
     ^~~~~~~~~~~~~~~~~
C:\googleFruit\include/fruit/impl/fruit-config.h:83:3: note: suggested alternative: '_assert'
   __assume(0)
   ^
C:\googleFruit\include/fruit/impl/normalized_component_storage/normalized_bindings.defn.h:47:5: note: in expansion of macro 'FRUIT_UNREACHABLE'
     FRUIT_UNREACHABLE; // LCOV_EXCL_LINE
     ^~~~~~~~~~~~~~~~~
C:\googleFruit\include/fruit/impl/injector/injector_storage.defn.h: In member function 'fruit::impl::InvokeLambdaWithInjectedArgVector<AnnotatedSignature, Lambda, true, AnnotatedT, fruit::impl::meta::Vector<AnnotatedArgs ...>, fruit::impl::meta::Vector<Indexes ...> >::CPtr fruit::impl::InvokeLambdaWithInjectedArgVector<AnnotatedSignature, Lambda, true, AnnotatedT, fruit::impl::meta::Vector<AnnotatedArgs ...>, fruit::impl::meta::Vector<Indexes ...> >::operator()(fruit::impl::InjectorStorage&, fruit::impl::FixedSizeAllocator&)':
C:\googleFruit\include/fruit/impl/fruit-config.h:83:3: error: there are no arguments to '__assume' that depend on a template parameter, so a declaration of '__assume' must be available [-fpermissive]
   __assume(0)
   ^
C:\googleFruit\include/fruit/impl/injector/injector_storage.defn.h:467:7: note: in expansion of macro 'FRUIT_UNREACHABLE'
       FRUIT_UNREACHABLE; // LCOV_EXCL_LINE
       ^~~~~~~~~~~~~~~~~
C:\googleFruit\include/fruit/impl/fruit-config.h:83:3: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
   __assume(0)
   ^
C:\googleFruit\include/fruit/impl/injector/injector_storage.defn.h:467:7: note: in expansion of macro 'FRUIT_UNREACHABLE'
       FRUIT_UNREACHABLE; // LCOV_EXCL_LINE
       ^~~~~~~~~~~~~~~~~
C:\googleFruit\include/fruit/impl/injector/injector_storage.defn.h: In member function 'fruit::impl::InvokeLambdaWithInjectedArgVector<AnnotatedSignature, Lambda, true, AnnotatedT, fruit::impl::meta::Vector<AnnotatedArgs ...>, fruit::impl::meta::Vector<Indexes ...> >::CPtr fruit::impl::InvokeLambdaWithInjectedArgVector<AnnotatedSignature, Lambda, true, AnnotatedT, fruit::impl::meta::Vector<AnnotatedArgs ...>, fruit::impl::meta::Vector<Indexes ...> >::operator()(fruit::impl::InjectorStorage&, fruit::impl::SemistaticGraph<fruit::impl::TypeId, fruit::impl::NormalizedBinding>&, fruit::impl::FixedSizeAllocator&, fruit::impl::SemistaticGraph<fruit::impl::TypeId, fruit::impl::NormalizedBinding>::edge_iterator)':
C:\googleFruit\include/fruit/impl/fruit-config.h:83:3: error: there are no arguments to '__assume' that depend on a template parameter, so a declaration of '__assume' must be available [-fpermissive]
   __assume(0)
   ^
C:\googleFruit\include/fruit/impl/injector/injector_storage.defn.h:519:7: note: in expansion of macro 'FRUIT_UNREACHABLE'
       FRUIT_UNREACHABLE; // LCOV_EXCL_LINE
       ^~~~~~~~~~~~~~~~~
mingw32-make.exe[1]: *** [h.mk:97: Debug/main.cpp.o] Error 1
mingw32-make.exe[1]: Leaving directory 'C:/Users/darri/Desktop/dev3project/h'
mingw32-make.exe: *** [Makefile:5: All] Error 2
====0 errors, 7 warnings====

**Comment by djsing** [comment]
I get the exact same error when using c++11

**Comment by poletti-marco** [comment]
Thanks for the report.

How did you run cmake? Make sure that the compiler used by CMake to generate the header files is the same as the one you're using (i.e. `C:/mingw64/bin/g++.exe`).
CMake prints the compiler when you run it (at least on the first run).

If you use the same compiler and it still doesn't work, please post:
* The content of the generated `fruit/impl/fruit-config-base.h` file
* The output of the CMake command
* Your `Makefile`.

And I'll try to reproduce the issue.

**Comment by djsing** [comment]
Thank you, it appears I was using the msvc compiler by default.
