### ISSUE TITLE
Documentation Update For Factories without Arguments

### ISSUE THREAD

**Issue by Dig-Doug** [google/fruit#85]
Hi,

I'd like to suggest a change to the wiki -- github doesn't support PRs for wiki pages so I'm submitting an issue instead:

In the quick reference, it says:

> The INJECT() macro (and the equivalent Inject typedef) can also be used to inject factories in the special case when there are 0 assisted arguments; in this case they will bind a type of the form std::function<std::unique_ptr<MyClass>()> consistently with the cases with >0 assisted arguments.

I think it would be clearer if you replaced it with something like this (with an example):

> If you would like to inject a factory but do not need to supply any additional assisted arguments, you can create a component that supplies a `std::function<std::unique_ptr<MyClass>()>` by just binding the implementation, for example:

```
using MyClassFactory = std::function<std::unique_ptr<MyClass>();

fruit::Component<MyClassFactory> getMyClassFactoryComponent() {
  return fruit::createComponent().bind<MyClass, MyClassImpl>();
}
```

I've been trying to use this feature for a little while, but only just figured out the correct way to bind it (luckily there was a test :D). Originally, I was expecting that creating a component like this:

```
fruit::Component<MyClass> getMyClassComponent() {
  return fruit::createComponent().bind<MyClass, MyClassImpl>();
}
```

would also bind `std::function<std::unique_ptr<MyClass>()` automatically.

Thanks!

**Comment by poletti-marco** [comment]
Thanks for suggesting this!
I agree that it's more clear that way.

I updated the wiki now.
